Introduced a method, SwitchBaseURL(), enabling the selection of alter…
cyruzin/golang-tmdb pull request #42
Opened 2023-04-14 09:01 UTC by allanpk716

Introduced a method, SwitchBaseURL(), enabling the selection of alternative API base URLs to accommodate varying network conditions across countries.

# Description

In my country, accessing api.themoviedb.org is restricted in many regions, while api.tmdb.org remains accessible. The proposed enhancement allows for switching the base API URL, such as with SwitchBaseURL(TMDB), prior to invoking Init().

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

All test cases from the original project have passed. Utilizing the new SwitchBaseURL(TMDB) function yields accurate results when querying data as well.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-14 13:38 UTC, cyruzin commented on authentication.go
> +// 	tmdbURL := fmt.Sprintf("%s%stoken/validate_with_login?api_key=%s", hhddjgetBaseURL(), authenticationURL, c.apiKey)
hhddjgetBaseURL() ?

2023-04-14 13:52 UTC, cyruzin requested changes
Can you implement like this?

```
// TMDb constants
const (
	defaultBaseURL    = "https://api.themoviedb.org/3"
	alternateBaseURL  = "https://api.tmdb.org/3"
	permissionURL     = "https://www.themoviedb.org/authenticate/"
	authenticationURL = "/authentication/"
	movieURL          = "/movie/"
	tvURL             = "/tv/"
	tvSeasonURL       = "/season/"
	tvEpisodeURL      = "/episode/"
	personURL         = "/person/"
	searchURL         = "/search/"
	collectionURL     = "/collection/"
	companyURL        = "/company/"
	configurationURL  = "/configuration/"
	creditURL         = "/credit/"
	discoverURL       = "/discover/"
	networkURL        = "/network/"
	keywordURL        = "/keyword/"
	genreURL          = "/genre/"
	guestSessionURL   = "/guest_session/"
	listURL           = "/list/"
	accountURL        = "/account/"
	watchProvidersURL = "/watch/providers/"
)

var baseURL = defaultBaseURL

// SetAlternateBaseURL sets an alternate base url.
func (c *Client) SetAlternateBaseURL() {
	baseURL = alternateBaseURL
}
```

2023-04-14 13:52 UTC, cyruzin commented on authentication.go
> +// 	tmdbURL := fmt.Sprintf("%s%ssession/convert/4?api_key=%s", hhddjgetBaseURL(), authenticationURL, c.apiKey)
here too: hhddjgetBaseURL() ?

2023-04-15 03:09 UTC, allanpk716 commented
Your improved solution is better, I think I can withdraw this is feature merge request. I'll resubmit it after I've reworked it.

2023-04-15 03:09 UTC, closed without merging